### ISSUE TITLE
Saving Groups

### ISSUE THREAD

**Issue by Aummadour** [feonor21/EveMiningFleetLog#1]
Feature request.  Saving your group between fleet.  Currently having to resign in all alts to create a group for each fleet.

**Comment by feonor21** [comment]
hello :)
if i understand,
when you create a fleet, you want to be able to add all your alt at once?

**Comment by Aummadour** [comment]
Would like my alts associated with my account.  So when I create a fleet, my alts are automatically added or can be added with a simple click to the fleet.

**Comment by feonor21** [comment]
OK, I will analyze what I can do.
can be like a seat. but this function can be quite heavy to develop.
but I will try :D 

thanks for your feedback :)

**Comment by feonor21** [comment]
Good news :D

with my front-end developer,

we are currently working on the graphic redesign of the reports.
and we will integrate the feature you want at the same time :D

it's not for now, but we are working on it.

fly safe :)

**Comment by feonor21** [comment]
with much (too much) time.

I have deployed the modification you asked me :) 

the management of the multi account, and the right kick

Looking forward to see you using the website again :)
