### ISSUE TITLE
Repeating Characters in Fleet

### ISSUE THREAD

**Issue by Aummadour** [feonor21/EveMiningFleetLog#3]
The main character gets listed as an alt twice in fleet.  Creating a situation where more than 100% of the total ore mined is calculated.

**Comment by feonor21** [comment]
hi 
Thank for your feedback
can you tell me your fleet ID?

in adresse of repport  https://eveminingfleet.ovh/Fleets/Details?FleetId=160
it is 160 for this example

**Comment by feonor21** [comment]
hoooo i see.

I'm working on it right now.

**Comment by feonor21** [comment]
I still make some test and I send the modification :)

**Comment by feonor21** [comment]
you can make a new fleet that should be fixed :)

thanks again for your feedback
