### ISSUE TITLE
Redistribution by volume issue

### ISSUE THREAD

**Issue by ThonolanScaldis** [feonor21/EveMiningFleetLog#4]
Hello,

Can you please make it so that the redistribution by volume is calculated on m3 instead of pcs? 
As an example: 2 identical vessels, same time, same amount mined but 1 mines veldspar and he other plagioclase. The one mining veld gets 4 times more ore but the same m3 as the one mining plagio. When redistributing by volume they should get 50/50 share and not 80/20.

Thanks,

Thonolan

**Comment by feonor21** [comment]
good evening

currently the redistribution by volume is based on the volume not the quantity :/
could you give me your fleet id so I can look at it in more detail?

**Comment by feonor21** [comment]
for know your ID of your fleet
in url adress :=> https://eveminingfleet.ovh/Fleets/Details?FleetId=30
id is 30 in this example

**Comment by ThonolanScaldis** [comment]
Good evening, 
Fleet detail is as follows. It was very visible in the beginning of the fleet as we all mined different ore. https://eveminingfleet.ovh/Fleets/Details?FleetId=188

**Comment by feonor21** [comment]
Good morning,

Based to the mining log. (the last section of the fleet report)
all the people are mining the same ore.
```
Plagioclase Azure Plagioclase
Scordite Condensed Scordite
Veldspar Concentrated Veldspar
```
in different quantities.

By this mining log for each character :
```
	Thonolan Scaldis			133,984.25 m3
	Joe Saventhas				347,338.15 m3
		Total for this group		481,322.4 m3(46,74%)
```

```
	Roast turkey				199,283.15 m3
	Tasty Pork				348,977.60 m3
		Total for this group		548 260,75(53,25%)
```


For the redistribution by volume,
All the ores are put together, 
then each group takes the amount (percentage) that they have mined 
(percentage = volume mined by the group / volume mined by the fleet)

For the redistribution by volume,
All the ores are put together, then each group takes the amount (percentage) they have mined (percentage = volume mined by the group / volume mined by the fleet)

so for Concentrated Veldspar 2,664,042(quantity for this fleet)
Thonolan Scaldis receives 2 664 042 x 46.74% = 1 245 415
Roast turkey receives 2 664 042 x 53.25% = 1 418 618

I'm sorry but I don't see any mistake :/
